services:
  #elasticsearch:
   # image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    #container_name: elasticsearch
    #environment:
     # - discovery.type=single-node
     # - xpack.security.enabled=false #OVO je samo za lokalni razvoj
     # - bootstrap.memory_lock=true
     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    #ports:
    #  - "9300:9300"
    #  - "9200:9200"
    #volumes:
    #  - es_data:/usr/share/elasticsearch/data

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
      - FLASK_ENV=development
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASS=${ELASTIC_PASS}
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"

volumes:
  es_data:
