services:
  #elasticsearch:
   # image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    #container_name: elasticsearch
    #environment:
     # - discovery.type=single-node
     # - xpack.security.enabled=false #OVO je samo za lokalni razvoj
     # - bootstrap.memory_lock=true
     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    #ports:
    #  - "9300:9300"
    #  - "9200:9200"
    #volumes:
    #  - es_data:/usr/share/elasticsearch/data

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    container_name: flask
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules        # DODAJ OVO (izolira teške module)
    container_name: react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true   # DODAJ OVO (za novije verzije)
      - WDS_SOCKET_PORT=0        # DODAJ OVO (popravlja websocket na Windowsima)
    env_file:
      - ./frontend/.env

volumes:
  es_data:
