# Klase za pojedine teme
topic_labels = {
    "business": {
        "Economy": ["inflation", "gdp", "recession", "economic", "market", "unemployment"],
        "Finance": ["stocks", "investment", "fund", "shares", "portfolio", "dividend", "trading", "nasdaq", "dow jones", "wall street"],
        "Politics": ["government", "policy", "regulation", "minister", "law", "tax", "election"],
        "Corporate": ["company", "merger", "acquisition", "business deal", "ceo", "startup", "partnership"],
        "Real Estate": ["real estate", "housing", "property", "mortgage", "rent", "construction"],
    },
    "sports": {
        "Football": ["football", "nfl", "quarterback", "touchdown", "soccer", "goal", "epl", "premier league"],
        "Basketball": ["nba", "basketball", "lebron", "curry", "slam dunk", "shooting guard"],
        "Baseball": ["baseball", "mlb", "pitcher", "homerun", "bat", "strike", "yankees"],
        "Tennis": ["tennis", "grand slam", "wimbledon", "djokovic", "nadal", "federer", "us open"],
        "Motorsport": ["formula 1", "f1", "motogp", "racing", "grand prix", "verstappen", "leclerc"],
        "Fight": ["boxing", "ufc", "mma", "knockout", "champion", "title fight", "conor mcgregor"],
        "Sneakers": ["sneakers", "kicks", "jordan", "nike", "adidas", "limited edition", "collab", "puma"],
    },
    "entertainment": {
        "Movies": ["movie", "film", "cinema", "box office", "director", "actor", "oscars", "blockbuster"],
        "Music": ["music", "album", "song", "concert", "tour", "artist", "spotify", "grammy", "singer", "band"],
        "TV Shows": ["tv series", "netflix", "hbo", "show", "episode", "season", "streaming", "max", "disney+", "hulu", "apple tv"],
        "Celebrities": ["celebrity", "scandal", "paparazzi", "gossip", "interview", "famous"],
        "Awards": ["oscars", "grammy", "emmy", "award", "nominee", "red carpet"],
        "Gaming": [
            "gaming",
            "video game",
            "esports",
            "streaming",
            "twitch",
            "gamer",
            "playstation",
            "xbox",
            "nintendo",
            "pc gaming",
            "mobile gaming",
            "vr gaming",
            "League of Legends",
            "Fortnite",
            "Call of Duty",
            "Minecraft",
        ],
    },
    "technology": {
        "AI": [
            "artificial intelligence",
            "machine learning",
            "deep learning",
            "neural network",
            "chatgpt",
            "openai",
            "gemini",
            "llm",
            "gpt-4",
            "gpt-3.5",
            "perplexity",
            "deepseek",
            "meta",
            "mistral",
            "llama",
        ],
        "Software": [
            "app",
            "application",
            "platform",
            "saas",
            "web",
            "devops",
            "frontend",
            "backend",
            "cloud",
            "software development",
            "programming",
            "javascript",
            "python",
            "java",
            "c++",
            "ruby",
            "php",
        ],
        "Hardware": [
            "chip",
            "gpu",
            "cpu",
            "semiconductor",
            "processor",
            "device",
            "quantum",
            "blockchain",
            "cryptocurrency",
            "bitcoin",
            "ethereum",
            "mining",
            "nvidia",
            "amd",
            "intel",
        ],
        "Cybersecurity": [
            "hacking",
            "breach",
            "cyberattack",
            "ransomware",
            "phishing",
            "firewall",
            "encryption",
            "data protection",
            "malware",
            "antivirus",
            "vpn",
        ],
        "Gadgets": [
            "smartphone",
            "tablet",
            "smartwatch",
            "device",
            "wearable",
            "iphone",
            "android",
            "apple",
            "samsung",
            "google",
            "smart home",
            "iot",
            "macbook",
            "ipad",
            "laptop",
            "desktop",
            "smart speaker",
            "vr headset",
            "drone",
        ],
    },
    "health": {
        "Diseases": ["cancer", "diabetes", "covid", "virus", "infection", "epidemic", "flu", "corona", "coronavirus", "pandemic"],
        "Nutrition": ["diet", "nutrition", "healthy food", "vitamin", "meal", "calorie", "supplement"],
        "Fitness": ["exercise", "workout", "gym", "training", "yoga", "cardio", "muscle"],
        "Mental Health": ["depression", "anxiety", "therapy", "psychologist", "stress", "mental health"],
        "Medical Research": ["vaccine", "trial", "medical study", "pharmaceutical", "treatment", "drug"],
        "Healthcare": ["healthcare", "hospital", "clinic", "doctor", "nurse", "health insurance", "health system"],
    },
    "science": {
        "Space": ["nasa", "space", "astronomy", "mars", "rocket", "telescope", "spacex", "asteroid", "black hole", "galaxy", "universe"],
        "Physics": ["quantum", "physics", "particle", "atom", "theory", "relativity", "hadron", "energy"],
        "Biology": ["biology", "genetics", "evolution", "cell", "organism", "dna", "neuroscience"],
        "Environment": ["climate", "pollution", "global warming", "carbon", "environment", "sustainability", "disaster"],
        "Chemistry": ["chemistry", "chemical", "reaction", "compound", "molecule", "laboratory", "experiment"],
    },
}
